from .users import User, UserCreate, UserUpdate
from .couleurs import Couleur, CouleurCreate, CouleurUpdate
from .projets import Projet, ProjetCreate, ProjetUpdate
from .palettes import Palette, PaletteCreate, PaletteUpdate
from .images import Image, ImageCreate, ImageUpdate
from .pixelarts import PixelArt, PixelArtCreate, PixelArtUpdate
from .reponses import Reponse, ReponseCreate, ReponseUpdate
from .assopalettecouleur import AssoPaletteCouleur, AssoPaletteCouleurCreate, AssoPaletteCouleurUpdate
from .assoprojetimage import AssoProjetImage, AssoProjetImageCreate, AssoProjetImageUpdate
from .assoprojetpalette import AssoProjetPalette, AssoProjetPaletteCreate, AssoProjetPaletteUpdate
from .assoprojetpalettereponse import AssoProjetPaletteReponse, AssoProjetPaletteReponseCreate, AssoProjetPaletteReponseUpdate
from .assoprojetpixelart import AssoProjetPixelArt, AssoProjetPixelArtCreate, AssoProjetPixelArtUpdate
from .assoprojetreponse import AssoProjetReponse, AssoProjetReponseCreate, AssoProjetReponseUpdate
from .assouserimage import AssoUserImage, AssoUserImageCreate, AssoUserImageUpdate
from .assouserpalette import AssoUserPalette, AssoUserPaletteCreate, AssoUserPaletteUpdate
from .assouserpixelart import AssoUserPixelArt, AssoUserPixelArtCreate, AssoUserPixelArtUpdate
from .assouserprojet import AssoUserProjet, AssoUserProjetCreate, AssoUserProjetUpdate
from .assouserreponse import AssoUserReponse, AssoUserReponseCreate, AssoUserReponseUpdate